# Generated by Django 4.0.3 on 2022-07-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/product')),
                ('price', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_data', models.DateTimeField(auto_now=True)),
                ('modified_data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
