# Generated by Django 4.0.3 on 2022-08-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
    ]
