# Generated by Django 4.0.3 on 2022-07-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categorys', 'verbose_name_plural': 'categories'},
        ),
    ]
